-- CREATE SCHEMA `portfolio_manager` ;
USE `portfolio_manager`;

DROP TABLE IF EXISTS `USER_ROLE_MAP`;
DROP TABLE IF EXISTS `USER_ROLE`;
DROP TABLE IF EXISTS `USER_CONTACT`;
DROP TABLE IF EXISTS `KPI_DATA`;
DROP TABLE IF EXISTS `KPI`;
DROP TABLE IF EXISTS `PROJECT`;
DROP TABLE IF EXISTS `PORTFOLIO`;
DROP TABLE IF EXISTS `SERVICE_OFFERING`;
DROP TABLE IF EXISTS `OPERATING_ENTITY`;
DROP TABLE IF EXISTS `COUNTRY`;
DROP TABLE IF EXISTS `USER`;