-- CREATE SCHEMA `portfolio_manager` ;
USE `portfolio_manager`;
-- Table USER_ROLE
CREATE TABLE `USER_ROLE` (
    `ID` BIGINT UNSIGNED NOT NULL PRIMARY KEY,
    `NAME` VARCHAR(255) NOT NULL,
	`DESCRIPTION` VARCHAR(255),
	`PRIORITY` INT,
	`ACTIVE` BOOLEAN
);

-- Table USER
CREATE TABLE `USER` (
    `ID` BIGINT UNSIGNED NOT NULL PRIMARY KEY,
	`FIRST_NAME` VARCHAR(255) NOT NULL,
    `LAST_NAME` VARCHAR(255),
	`USER_NAME` VARCHAR(255) NOT NULL,
	`PASSWORD` VARCHAR(255) NOT NULL
);

-- Table USER_ROLE_MAP
CREATE TABLE `USER_ROLE_MAP` (

	`USER_ID` BIGINT UNSIGNED NOT NULL,
	`USER_ROLE_ID` BIGINT UNSIGNED NOT NULL
);

-- Table USER_CONTACT
CREATE TABLE `USER_CONTACT` (
    `ID` BIGINT UNSIGNED NOT NULL PRIMARY KEY,
	`EMAIL` VARCHAR(255) NOT NULL,
    `PHONE_NUMBER` BIGINT,
	`USER_ID` BIGINT UNSIGNED
);

CREATE TABLE `PROJECT` (
    `ID` BIGINT UNSIGNED NOT NULL PRIMARY KEY,
    `PRJ_NAME` VARCHAR(255) NOT NULL,
	`PRJ_DESCRIPTION` TEXT,
	`DEPARTMENT` VARCHAR(255),
    `BUSINESS_WEIGHTAGE` INT,
    `DEVELOPMENT_METHODOLOGY` VARCHAR(255),
	`SERVICE_OWNER_IT_ID` BIGINT UNSIGNED,
	`SERVICE_OWNER_BUSINESS_ID` BIGINT UNSIGNED,
	`SERVICE_MANAGER_ID` BIGINT UNSIGNED,
	`PORTFOLIO_ID` BIGINT UNSIGNED
);

ALTER TABLE `PROJECT` ADD CONSTRAINT 
FK_PROJECT_SERVICE_OWNER_IT_ID FOREIGN KEY (`SERVICE_OWNER_IT_ID`) 
REFERENCES `USER` (`ID`);

ALTER TABLE `PROJECT` ADD CONSTRAINT 
FK_PROJECT_SERVICE_OWNER_BUSINESS_ID 
FOREIGN KEY (`SERVICE_OWNER_BUSINESS_ID`) REFERENCES `USER` (`ID`);

ALTER TABLE `PROJECT` ADD CONSTRAINT 
FK_PROJECT_SERVICE_MANAGER_ID FOREIGN KEY (`SERVICE_MANAGER_ID`) 
REFERENCES `USER` (`ID`);

ALTER TABLE `USER_CONTACT` ADD 
CONSTRAINT FK_USER_CONTACT_USR_ID 
FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`ID`)
ON DELETE CASCADE ON UPDATE CASCADE;


ALTER TABLE `USER_ROLE_MAP` 
ADD CONSTRAINT FK_USER_ROLE_MAP_USR_ID 
FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`ID`);

ALTER TABLE `USER_ROLE_MAP` ADD 
CONSTRAINT FK_USER_ROLE_MAP_USER_ROLE_ID 
FOREIGN KEY (`USER_ROLE_ID`) REFERENCES `USER_ROLE` (`ID`)
ON DELETE CASCADE;

ALTER TABLE `USER` ADD CONSTRAINT UN_USER_NAME 
UNIQUE (USER_NAME);

ALTER TABLE `USER_ROLE_MAP` 
ADD CONSTRAINT UN_USER_ROLE_MAP_USER_ROLE 
UNIQUE (USER_ID, USER_ROLE_ID);