USE `portfolio_manager`;

INSERT INTO USER_ROLE(ID, NAME, DESCRIPTION, PRIORITY, ACTIVE) 
VALUES (1, 'ADMIN', 'ADMIN', 1, True);
INSERT INTO USER_ROLE(ID, NAME, DESCRIPTION, PRIORITY, ACTIVE) 
VALUES (2, 'MANAGER', 'MANAGER', 2, True);
INSERT INTO USER_ROLE(ID, NAME, DESCRIPTION, PRIORITY, ACTIVE) 
VALUES (3, 'USER', 'USER', 3, True);

INSERT INTO USER(ID, FIRST_NAME, LAST_NAME, USER_NAME, PASSWORD) 
VALUES (1, 'Admin', 'Admin', 'admin', 'password@123');

INSERT INTO USER_ROLE_MAP( USER_ID, USER_ROLE_ID) 
VALUES ( 1, 1);

INSERT INTO USER_CONTACT(ID, EMAIL, PHONE_NUMBER, USER_ID) 
VALUES (1, 'user1@test.com', '00123456789', 1);